import yfinance as yf
import pandas as pd
import warnings

# Suppress warnings to ensure clean output
warnings.filterwarnings('ignore')

def calculate_macd_rsi():
    # Fetch TSMC data
    ticker = "2330.TW"
    # Fetch past 1 year of daily data
    df = yf.download(ticker, period="1y", progress=False)
    
    # Handle yfinance multi-index columns if present
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = [col[0] for col in df.columns]

    # Ensure data is sorted by date
    df.sort_index(inplace=True)

    # Forward fill missing values just in case, then drop remaining NaNs
    df = df.ffill().dropna()

    # Calculate MACD
    # MACD Line = 12-Period EMA - 26-Period EMA
    ema12 = df['Close'].ewm(span=12, adjust=False).mean()
    ema26 = df['Close'].ewm(span=26, adjust=False).mean()
    df['MACD'] = ema12 - ema26
    # Signal Line = 9-Period EMA of MACD Line
    df['MACD_Signal'] = df['MACD'].ewm(span=9, adjust=False).mean()
    df['MACD_Histogram'] = df['MACD'] - df['MACD_Signal']

    # Calculate 14-day RSI (Wilder's Smoothing)
    delta = df['Close'].diff()
    gain = delta.where(delta > 0, 0.0)
    loss = -delta.where(delta < 0, 0.0)
    
    # Wilder's smoothing is equivalent to an exponential moving average with alpha = 1/period
    # Note: to perfectly match traditional RSI, the first average should be a simple moving average,
    # but ewm with alpha=1/14 and adjust=False is widely used and accepted in pandas.
    avg_gain = gain.ewm(alpha=1/14, min_periods=14, adjust=False).mean()
    avg_loss = loss.ewm(alpha=1/14, min_periods=14, adjust=False).mean()
    
    rs = avg_gain / avg_loss
    df['RSI_14'] = 100 - (100 / (1 + rs))

    # Drop NaNs generated by technical indicator window periods
    df.dropna(inplace=True)

    # Return the last 10 trading days
    return df[['Close', 'MACD', 'MACD_Signal', 'MACD_Histogram', 'RSI_14']].tail(10)

if __name__ == "__main__":
    try:
        result = calculate_macd_rsi()
        # Print cleanly
        print(result.to_string())
    except Exception as e:
        print(f"Error occurred: {e}")
